name: CI/CD Testing and Deployment
on:
  push:
    branches:
      - main
jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install --include=dev
    - name: Install c8
      run: npm install c8 -g
  test:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: npm test
  lint:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
    - uses: actions/checkout@v2
    - name: Lint source
      run: npx eslint src/
    - name: Check for 100% test coverage
      run: c8 --100 npm test
  build:
    runs-on: ubuntu-latest
    needs: [ test, lint ]
    steps:
    - uses: actions/checkout@v2
    - name: Delete dist code
      run: rm -f dist/static/neighbors/bundle.js
    - name: Generate dist code
      run: npx webpack
