name: CI/CD Testing and Deployment
on:
  push:
    branches:
      - main
jobs:
  Test-Lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install general dependencies
      run: npm install --include=dev
    - name: Install c8
      run: npm install c8 -g
    - name: Run tests
      run: npm test
    - name: Lint source
      run: npx eslint src/
    - name: Check for 100% test coverage
      run: c8 --100 npm test
    - name: Delete dist code
      run: rm -f dist/static/neighbors/bundle.js
    - name: Generate dist code
      run: npx webpack
  Build-Deploy:
    runs-on: ubuntu-latest
    needs: Test-Lint
    steps:
    - uses: actions/checkout@v2
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-2'
        SOURCE_DIR: 'dist'
