name: CI Testing
on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  schedule:
    - cron: '22 13 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install --include=dev
    - name: Run tests
      run: npm test
    - name: Lint source
      run: npx eslint src/
    - name: Generate dist code
      run: npx webpack
    - name: Install c8
      run: npm install c8 -g
    - name: Check for 100% test coverage
      run: c8 --100 npm test
